Improve Error Handling in TreeTime
neherlab/treetime pull request #206
Opened 2022-09-02 14:00 UTC by anna-parker

# Related Issue and PR:

https://github.com/nextstrain/augur/issues/1032
https://github.com/nextstrain/augur/pull/1033

Building on @victorlin's suggestions in : https://github.com/neherlab/treetime/compare/44e7c56a1d10baa3d4dcdf07b5c7cd55d6d651e9...2632d96144ada719a33f966cc11c5bc118c987a4 I have made a couple minor changes to TreeTime's error handling process: 
 - more consistent labeling of error classes: rename errors due to incorrect input data or incorrect use of treetime as one of the three predefined TreeTime error classes: `MissingDataError`, `UnknownMethodError` and `NotReadyError`
 - add new `TreeTimeError` class for errors that might be due to input data not matching with assumptions or unknown behavior (potential bug): `TreeTimeOtherError`. 
 - call `treetime.run` in a wrapper to catch all errors with notification on how to report issues. i.e. `ERROR in TreeTime.run: An error has occurred which is not properly handled in TreeTime. If this error persists, please let us know "
                    "by filing a new issue including the original command and the error above at: https://github.com/neherlab/treetime/issues `
 - when run from another application, such as `augur` return all errors as `TreeTimeError`s but with distinction between input/usage errors and potential treetime bugs (these are output as `TreeTimeOtherError`s). On standard run print traceback for unknown errors / potential bugs, print warning and then exit treetime (avoid double printing of traceback or traceback after final warning). 
 
 Example for unknown `ValueError`: 
 
![image](https://user-images.githubusercontent.com/50943381/188157285-e75b2f2a-dfb7-4958-bbff-5968d3974aa7.png)

Example for known `MissingDataError`: 

![image](https://user-images.githubusercontent.com/50943381/188158102-165d144a-d145-4b0a-8944-248e434ad361.png)

I used the same example as in the PR above to create an error. I made two test cases, one where the error is called a `ValueError` which should be handled as a `TreeTimeOtherError` and another where the error is called a `MissingDataError`. 

# Testing
- install augur and treetime in local environment
- cause an Exception in treetime (either call this a `ValueError` or a `TreeTimeError`), I added a line in `_exp_lt`
```
        """
        Parameters
        ----------

         t : float
            time to propagate

        Returns
        --------

         exp_lt : numpy.array
            Array of values exp(lambda(i) * t),
            where (i) - alphabet index (the eigenvalue number).
        """
        log_val = self.mu * t * self.eigenvals
        log_val = np.ones(len(log_val))*750 ##cause an exception
        if any(i > 10 for i in log_val):
            raise ValueError("Error in computing exp(Q * t): Q has positive eigenvalues or the branch length t \n"
                    "is too large. This is most likely caused by incorrect input data.")

        return np.exp(log_val)
```
- install modified treetime in local environment `(pip install .`)
- call `treetime.run()` in a test script where it is not in a `try` - `catch` statement, for example: run `python test/treetime_algorithms.py`

2022-09-02 14:36 UTC, corneliusroemer requested changes
Still a bit confused what the error hierarchy is supposed to be :)

2022-09-02 14:36 UTC, corneliusroemer commented on treetime/__init__.py
>      """TreeTimeError class"""
```suggestion
    """
    TreeTimeError class
    Parent class for more specific errors
    Raised when treetime is used incorrectly in contrast with `TreeTimeOtherError`
    `TreeTimeOtherError` is raised when the reason of the error is unknown, could indicate bug     
    """
```

2022-09-02 14:36 UTC, corneliusroemer commented on treetime/__init__.py
> +    """MissingDataError class raised when an unknown method is called"""
Are methods added dynamically? In that case it may be helpful to explain this.

"alignment are missing" sounds like this error would be raised if you haven't loaded an alignment but call a method that gets added only during alignment

2022-09-02 14:36 UTC, corneliusroemer commented on treetime/__init__.py
> +class TreeTimeOtherError(TreeTimeError):
```suggestion
class TreeTimeOtherError(Exception):
```
Shouldn't make this a different parent class? I thought that's what we discussed earlier.

TreetimeError is specifically an error that treetime knows something about. Whereas other error could be a treetime bug.

Though this other error could still be inheriting from TreeTimeError, one would then just test whether the error is OtherError and handle that differently. So either works - but I thought we'd discussed differently :)

2022-09-02 14:36 UTC, corneliusroemer commented on treetime/__init__.py
>      pass
Or parameters are missing? If I understand usage below correctly?

2022-09-02 14:36 UTC, corneliusroemer commented on treetime/clock_tree.py
> +            raise MissingDataError("ClockTree requires date constraints!")
If this is how you want to use MissingDataError one should probably change the description of the MissingDataError to encompass missing parameters

2022-09-02 14:36 UTC, corneliusroemer commented on treetime/clock_tree.py
> +                raise UnknownMethodError(f"ClockTree: precision_fft needs to be either 'auto' or an integer, got '{precision_fft}'.")
This should be a new type of error? Something like: Wrong parameter passed - not unknown method. This has nothing to do with a method?

2022-09-02 14:36 UTC, corneliusroemer commented on treetime/gtr.py
> +            raise ValueError("Error in computing exp(Q * t): Q has positive eigenvalues or the branch length t is too large. "
Isn't this the type of error that should be wrapped by Augur? If so, it should maybe be "InputDataError"? Or is this what you use ValueError for now? Though I'd think ValueError would need to be TreetimeError - or is this supposed to be a "TreetimeOtherError"?

2022-09-07 07:57 UTC, merged

2022-09-07 09:23 UTC, anna-parker commented on treetime/treetime.py
> +    def run(self, augur=False, **kwargs):
@victorlin Hi, I modified how the `run` function is called to make sure that the Errors get printed at the correct location when running in `TreeTime` and in `augur` - however @corneliusroemer mentioned that using the argument `augur=true` is not the best coding practice - is there a better way to do this? Perhaps we could use @rneher `raise_uncaught_exception = true` instead as an argument to make it less specific and then add some commentary? Thanks for any input :-)

2022-09-08 00:02 UTC, victorlin reviewed
Post-merge requested changes

2022-09-08 00:02 UTC, victorlin commented on treetime/__init__.py
> +class TreeTimeOtherError(Exception):
"Other" seems a bit ambiguous... "other" than what?

```suggestion
class TreeTimeUnknownError(Exception):
```

2022-09-08 00:02 UTC, victorlin commented on treetime/treetime.py
> +    def run(self, augur=False, **kwargs):
I agree, naming this parameter as `augur` seems too specific – it's possible that other Python scripts would want to use this too. `raise_uncaught_exceptions` (plural) is nice self-describing name.

2022-09-08 00:02 UTC, victorlin commented on treetime/treetime.py
> +                    "by filing a new issue including the original command and the error above at: https://github.com/neherlab/treetime/issues \n", file=sys.stderr)
Minor grammar:

```suggestion
            print("ERROR in TreeTime.run: An error occurred which was not properly handled in TreeTime. If this error persists, please let us know "
                    "by filing a new issue including the original command and the error above at: https://github.com/neherlab/treetime/issues \n", file=sys.stderr)
```

2022-09-08 00:02 UTC, victorlin commented on treetime/treetime.py
> +                sys.exit(2)
No need to print the error if it is being raised:

```suggestion
        except TreeTimeError as err:
            if augur:
                raise err
            else:
                print(f"ERROR: {err} \n", file=sys.stderr)
                sys.exit(2)
```

2022-09-08 00:02 UTC, victorlin commented on treetime/treetime.py
> +            print(traceback.format_exc())
Traceback should be printed to stderr to as well:

```suggestion
            print(traceback.format_exc(), file=sys.stderr)
```

2022-09-08 06:29 UTC, anna-parker commented
@victorlin thanks so much for your suggestions - I have added them to another branch https://github.com/neherlab/treetime/tree/feat/victor-error-handling - will do a PR after checking they integrate with your suggestions in augur :-)

2022-09-08 14:44 UTC, corneliusroemer commented on treetime/__init__.py
> +class TreeTimeOtherError(Exception):
I like unknown